---
title: "WI Stream Classes - Exploratory Analyses"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
ragg_png = function(..., res = 150) {
  ragg::agg_png(..., res = res, units = "in")
}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, 
                      dev = "ragg_png", res = 500, retina = 1)
```


```{r prep, warning=FALSE, message=FALSE}
# packages
library(tidyverse)  # data manipulation
library(cluster)    # clustering algorithms
library(factoextra) # clustering algorithms & visualization
library(patchwork)  # panel plots

```

## Data

```{r data}
# read in
df_fish_pa <- readRDS(here::here("data", "df_fish_pa.rds"))
df_fish_pa_sport <- readRDS(here::here("data", "df_fish_pa_sport.rds"))

# make rownames
df <- df_fish_pa %>% column_to_rownames("reach_id")
dfs <- df_fish_pa_sport %>% column_to_rownames("reach_id")

```

## k-mean cluster analysis

### All species P/A

```{r}
k2 <- kmeans(df, centers = 2, nstart = 25)
k3 <- kmeans(df, centers = 3, nstart = 25)
k4 <- kmeans(df, centers = 4, nstart = 25)
k5 <- kmeans(df, centers = 5, nstart = 25)

```

### Plots to compare
```{r plot-k-means-all-fish, fig.align='center', fig.width=12, fig.height=8}
p1 <- fviz_cluster(k2, geom = "point", data = df) + ggtitle("k = 2")
p2 <- fviz_cluster(k3, geom = "point",  data = df) + ggtitle("k = 3")
p3 <- fviz_cluster(k4, geom = "point",  data = df) + ggtitle("k = 4")
p4 <- fviz_cluster(k5, geom = "point",  data = df) + ggtitle("k = 5")

(p.all.spp <- (p1 + p2) / (p3 + p4) )

```


### Only sportfish P/A

```{r}
k2s <- kmeans(dfs, centers = 2, nstart = 25)
k3s <- kmeans(dfs, centers = 3, nstart = 25)
k4s <- kmeans(dfs, centers = 4, nstart = 25)
k5s <- kmeans(dfs, centers = 5, nstart = 25)

```


### Plots to compare
```{r plot-k-means-sportfish, fig.align='center', fig.width=12, fig.height=8}
p1s <- fviz_cluster(k2s, geom = "point", data = dfs) + ggtitle("k = 2")
p2s <- fviz_cluster(k3s, geom = "point",  data = dfs) + ggtitle("k = 3")
p3s <- fviz_cluster(k4s, geom = "point",  data = dfs) + ggtitle("k = 4")
p4s <- fviz_cluster(k5s, geom = "point",  data = dfs) + ggtitle("k = 5")

(p.sportfish <- (p1s + p2s) / (p3s + p4s) )


```


*** 

## Session Info

```{r session}
Sys.time()
# git2r::repository()
sessionInfo()
```